# Generated by Django 4.2.11 on 2024-08-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
