# Generated by Django 4.2.11 on 2024-08-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_subject_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(null=True, to='api.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(null=True, to='api.subject'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.class'),
        ),
    ]
