# Generated by Django 4.2.11 on 2024-08-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_attendance_student_alter_class_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='api.student'),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='api.subject'),
        ),
    ]
