# Generated by Django 4.2.11 on 2024-08-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_student_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_grade',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
